//! Cross-route acceptance over real identity HTTP and verified signed records.
mod common;
#[path = "common/identity.rs"]
mod identity;
#[path = "common/read_projection.rs"]
mod projection;

use atmusic_server::auth::session;
use chrono::{DateTime, SecondsFormat, Utc};
use identity::{ALICE, BOB, CAROL, ControlledIdentity};
use projection::{AS_OF, CANONICAL_AS_OF, ReadFixtures};
use serde_json::{Value, json};
use std::sync::{Arc, atomic::AtomicI64};

struct Harness {
    server: common::TestServer,
    identity: ControlledIdentity,
    fixtures: ReadFixtures,
    cookie: String,
}
impl Harness {
    async fn new() -> Self {
        let identity = ControlledIdentity::start().await;
        let server = common::TestServer::start_with_state(
            Arc::new(projection::FixedClock(AtomicI64::new(1_768_478_400))),
            |state| state.with_identity(identity.resolver.clone()),
        )
        .await;
        let fixtures = projection::seed(&server, true).await;
        let issued = session::issue(
            &server.database,
            server.state.config.as_ref().unwrap().encryption_key(),
            ALICE,
            server.state.clock.now(),
        )
        .await
        .unwrap();
        Self {
            server,
            identity,
            fixtures,
            cookie: issued.cookie,
        }
    }
    async fn get(&self, path: &str, authenticated: bool) -> Value {
        let request = self.server.client.get(self.server.url(path));
        let response = if authenticated {
            request.header("cookie", &self.cookie)
        } else {
            request
        }
        .send()
        .await
        .unwrap();
        assert_eq!(response.status(), 200, "{path}");
        let body = response.text().await.unwrap();
        for private in [
            "accessToken",
            "refreshToken",
            "encrypted_material",
            "payload_json",
            "csrfToken",
        ] {
            assert!(!body.contains(private), "private field in {path}");
        }
        serde_json::from_str(&body).unwrap()
    }
    async fn expected(&self, did: &str, rkey: &str) -> Value {
        let source: Value =
            serde_json::from_str(include_str!("../../../tests/fixtures/read_models.json")).unwrap();
        let original = source["scrobbles"]
            .as_array()
            .unwrap()
            .iter()
            .find(|row| row["owner"] == did && row["rkey"] == rkey)
            .unwrap();
        let mut row = original["record"].clone();
        row.as_object_mut().unwrap().remove("$type");
        for field in ["listenedAt", "createdAt"] {
            row[field] = json!(
                DateTime::parse_from_rfc3339(row[field].as_str().unwrap())
                    .unwrap()
                    .with_timezone(&Utc)
                    .to_rfc3339_opts(SecondsFormat::Nanos, true)
            );
        }
        let uri = projection::uri(did, rkey);
        // CID is generated by the signed fixture. Expected content/order comes
        // from the frozen source fixture, independently of production queries.
        let cid = self
            .server
            .database
            .repositories()
            .scrobble(&uri)
            .await
            .unwrap()
            .unwrap()
            .cid;
        row["uri"] = json!(uri);
        row["cid"] = json!(cid);
        row["did"] = json!(did);
        row["revision"] = json!("3m3ijqc2abc22");
        row["indexedAt"] = json!(CANONICAL_AS_OF);
        row
    }
    async fn expected_rows(&self, rows: &[(&str, &str)]) -> Value {
        let mut items = Vec::new();
        for (did, rkey) in rows {
            items.push(self.expected(did, rkey).await);
        }
        json!(items)
    }
}
fn all_stats() -> Value {
    json!({"did":ALICE,"window":"all","asOf":CANONICAL_AS_OF,"totalScrobbles":7,"distinctArtists":3,"distinctTracks":6,
        "topArtists":[{"artist":"Radiohead","scrobbleCount":3},{"artist":"Björk","scrobbleCount":2},{"artist":"Kate Bush","scrobbleCount":2}],
        "topTracks":[{"artist":"Björk","track":"Jóga","scrobbleCount":2},{"artist":"Kate Bush","track":"Cloudbusting","scrobbleCount":1},{"artist":"Kate Bush","track":"Running Up That Hill","scrobbleCount":1},{"artist":"Radiohead","track":"Karma Police","scrobbleCount":1},{"artist":"Radiohead","track":"No Surprises","scrobbleCount":1},{"artist":"Radiohead","track":"Weird Fishes","scrobbleCount":1}],
        "topAlbums":[{"artist":"Björk","album":"Homogenic","scrobbleCount":2},{"artist":"Radiohead","album":"OK Computer","scrobbleCount":2},{"artist":"Kate Bush","album":"Hounds of Love","scrobbleCount":1},{"artist":"Radiohead","album":"In Rainbows","scrobbleCount":1}]})
}
fn assert_page_metadata(body: &Value) {
    assert_eq!(body.as_object().unwrap().len(), 4);
    assert_eq!(body["asOf"], CANONICAL_AS_OF);
    assert_eq!(
        body["indexing"],
        json!({"state":"recovering","caughtUp":false,"lastIndexedAt":null,"lagSeconds":null})
    );
}

#[tokio::test]
async fn read_acceptance() {
    let harness = Harness::new().await;
    assert_eq!(
        harness
            .get(&format!("/api/v1/users/{ALICE}/stats?window=all"), false)
            .await,
        all_stats()
    );
    let alice = [
        (ALICE, "r07"),
        (ALICE, "r01"),
        (ALICE, "r02"),
        (ALICE, "r03"),
        (ALICE, "r04"),
        (ALICE, "r05"),
        (ALICE, "r06"),
    ];
    let expected = harness.expected_rows(&alice).await;
    let history = harness
        .get(&format!("/api/v1/users/{ALICE}/scrobbles"), false)
        .await;
    assert_page_metadata(&history);
    assert_eq!(history["items"], expected);
    assert_eq!(history["nextCursor"], Value::Null);
    let global = harness.get("/api/v1/feed?scope=global", false).await;
    assert_page_metadata(&global);
    assert_eq!(
        global["items"],
        harness
            .expected_rows(&[
                (BOB, "r09"),
                (CAROL, "r10"),
                (ALICE, "r07"),
                (ALICE, "r01"),
                (ALICE, "r02"),
                (ALICE, "r03"),
                (ALICE, "r04"),
                (ALICE, "r05"),
                (ALICE, "r06")
            ])
            .await
    );
    let following = harness.get("/api/v1/feed?scope=following", true).await;
    assert_eq!(
        following["items"],
        harness.expected_rows(&[(BOB, "r09")]).await
    );
    let resolved = harness
        .get("/api/v1/resolve?handle=alice.test", false)
        .await;
    assert_eq!(
        resolved,
        json!({"did":ALICE,"handle":"alice.test","verified":true})
    );
    let profile = harness
        .get(&format!("/api/v1/users/{ALICE}/profile"), false)
        .await;
    assert_eq!(
        profile,
        json!({"did":ALICE,"handle":"alice.test","joinedAt":"2025-01-01T00:00:00.000000000Z","indexedAt":CANONICAL_AS_OF,"totalScrobbles":7,"followerCount":0,"followingCount":1,"indexing":{"state":"recovering","caughtUp":false,"lastIndexedAt":null,"lagSeconds":null}})
    );
    let mut path = format!("/api/v1/users/{ALICE}/scrobbles?limit=2");
    let mut pages = Vec::new();
    let mut lengths = Vec::new();
    loop {
        let page = harness.get(&path, false).await;
        assert_page_metadata(&page);
        lengths.push(page["items"].as_array().unwrap().len());
        pages.extend(page["items"].as_array().unwrap().clone());
        match page["nextCursor"].as_str() {
            Some(cursor) => {
                let query = url::form_urlencoded::Serializer::new(String::new())
                    .append_pair("limit", "2")
                    .append_pair("cursor", cursor)
                    .finish();
                path = format!("/api/v1/users/{ALICE}/scrobbles?{query}");
            }
            None => break,
        }
    }
    assert_eq!(lengths, [2, 2, 2, 1]);
    assert_eq!(json!(pages), expected);
    assert_eq!(
        sqlx::query_scalar::<_, i64>("SELECT count(*) FROM operations")
            .fetch_one(harness.server.database.reader_pool())
            .await
            .unwrap(),
        0
    );
    assert!(!harness.server.shutdown().await.timed_out);
}

#[tokio::test]
async fn social_acceptance() {
    let mut harness = Harness::new().await;
    let global = harness.get("/api/v1/feed?scope=global", false).await;
    let bob = harness
        .get(&format!("/api/v1/users/{BOB}/scrobbles"), false)
        .await;
    assert_eq!(
        harness.get("/api/v1/feed?scope=following", true).await["items"],
        harness.expected_rows(&[(BOB, "r09")]).await
    );
    harness
        .fixtures
        .delete(&harness.server, ALICE, &projection::follow_uri(ALICE, BOB))
        .await;
    assert_eq!(
        harness.get("/api/v1/feed?scope=following", true).await["items"],
        json!([])
    );
    assert_eq!(
        harness.get("/api/v1/feed?scope=global", false).await,
        global
    );
    assert_eq!(
        harness
            .get(&format!("/api/v1/users/{BOB}/scrobbles"), false)
            .await,
        bob
    );
    assert_eq!(
        harness
            .get(&format!("/api/v1/users/{ALICE}/profile"), false)
            .await["followingCount"],
        0
    );
    let rkey = atmusic_core::follow::follow_rkey(BOB).unwrap();
    harness
        .fixtures
        .put_follow(&harness.server, ALICE, &rkey, BOB)
        .await;
    assert_eq!(
        harness.get("/api/v1/feed?scope=following", true).await["items"],
        harness.expected_rows(&[(BOB, "r09")]).await
    );
    assert_eq!(
        harness.get("/api/v1/feed?scope=global", false).await,
        global
    );
    let follows = harness
        .get(&format!("/api/v1/users/{ALICE}/following"), false)
        .await;
    assert_eq!(follows["items"].as_array().unwrap().len(), 1);
    assert_eq!(
        follows["items"][0]["uri"],
        projection::follow_uri(ALICE, BOB)
    );
    assert_eq!(follows["items"][0]["actor"], ALICE);
    assert_eq!(follows["items"][0]["subject"], BOB);
    assert_eq!(
        harness
            .server
            .database
            .repositories()
            .public_counts(BOB)
            .await
            .unwrap()
            .1,
        1
    );
    assert!(!harness.server.shutdown().await.timed_out);
}

#[tokio::test]
async fn mutation_acceptance() {
    let mut harness = Harness::new().await;
    let initial_profile = harness
        .get(&format!("/api/v1/users/{ALICE}/profile"), false)
        .await;
    harness.fixtures.put(&harness.server,ALICE,"r03",json!({"artist":"Björk","track":"Weird Fishes","album":"In Rainbows","listenedAt":"2026-01-08T12:00:00Z","createdAt":AS_OF})).await;
    let changed = harness
        .get(&format!("/api/v1/users/{ALICE}/stats?window=all"), false)
        .await;
    assert_eq!(changed["totalScrobbles"], 7);
    assert_eq!(changed["distinctTracks"], 6);
    assert_eq!(
        changed["topArtists"],
        json!([{"artist":"Björk","scrobbleCount":3},{"artist":"Kate Bush","scrobbleCount":2},{"artist":"Radiohead","scrobbleCount":2}])
    );
    harness
        .fixtures
        .delete(&harness.server, ALICE, &projection::uri(ALICE, "r01"))
        .await;
    let deleted = harness
        .get(&format!("/api/v1/users/{ALICE}/stats?window=all"), false)
        .await;
    assert_eq!(deleted["totalScrobbles"], 6);
    assert_eq!(deleted["distinctArtists"], 3);
    assert_eq!(deleted["distinctTracks"], 6);
    assert_eq!(
        deleted["topArtists"],
        json!([{"artist":"  BJÖRK  ","scrobbleCount":2},{"artist":"Kate Bush","scrobbleCount":2},{"artist":"Radiohead","scrobbleCount":2}])
    );
    let history = harness
        .get(&format!("/api/v1/users/{ALICE}/scrobbles"), false)
        .await;
    assert_eq!(
        projection::items(&history),
        ["r07", "r02", "r03", "r04", "r05", "r06"].map(|key| projection::uri(ALICE, key))
    );
    assert_eq!(history["items"][2]["artist"], "Björk");
    harness.identity.rename(ALICE, "renamed.test");
    harness.identity.clock.set(300);
    assert_eq!(
        harness
            .get("/api/v1/resolve?handle=renamed.test", false)
            .await,
        json!({"did":ALICE,"handle":"renamed.test","verified":true})
    );
    let renamed = harness
        .get(&format!("/api/v1/users/{ALICE}/profile"), false)
        .await;
    assert_eq!(renamed["did"], initial_profile["did"]);
    assert_eq!(renamed["joinedAt"], initial_profile["joinedAt"]);
    assert_eq!(renamed["handle"], "renamed.test");
    assert_eq!(renamed["totalScrobbles"], 6);
    assert_eq!(
        harness
            .get(&format!("/api/v1/users/{ALICE}/scrobbles"), false)
            .await,
        history
    );
    assert_eq!(
        sqlx::query_scalar::<_, i64>("SELECT count(*) FROM users")
            .fetch_one(harness.server.database.reader_pool())
            .await
            .unwrap(),
        3
    );
    assert!(!harness.server.shutdown().await.timed_out);
}
