[package]
name = "atmusic-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
base64 = "=0.22.1"
chrono = { version = "=0.4.42", default-features = false, features = ["std", "serde"] }
hmac = "=0.12.1"
sha2 = "=0.10.9"
caseless = "=0.2.2"
unicode-normalization = "=0.1.24"

[lints]
workspace = true
